/**
 * Shared XSL presentation for every sitemap.
 *
 * This is browser chrome only - crawlers ignore it, and the sitemap XML stays
 * valid and complete if the stylesheet is never fetched. It handles both root
 * element types: `<sitemapindex>` renders a "Sitemap" column, `<urlset>`
 * renders a "URL" column, and the "Images" column appears only when the
 * document genuinely contains image entries.
 *
 * No JavaScript and no external stylesheet or font dependencies, so it renders
 * identically offline and cannot leak a request to a third party.
 */
export const SITEMAP_STYLESHEET = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  exclude-result-prefixes="s image">

  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"
    doctype-system="about:legacy-compat" />

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="noindex, follow" />
        <title>XML Sitemap | The Building Practice Ltd.</title>
        <style>
          :root {
            --ink: #111827;
            --muted: #4b5563;
            --line: #e5e7eb;
            --stripe: #f7f8f9;
            --brand: #1a5f7a;
            --accent: #c9a227;
          }
          * { box-sizing: border-box; }
          body {
            margin: 0;
            background: #ffffff;
            color: var(--ink);
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            font-size: 16px;
            line-height: 1.6;
            -webkit-text-size-adjust: 100%;
          }
          .wrap { max-width: 1100px; margin: 0 auto; padding: 40px 20px 72px; }
          .brand {
            display: flex; align-items: baseline; flex-wrap: wrap; gap: 10px;
            padding-bottom: 20px; border-bottom: 3px solid var(--brand);
          }
          .brand-name { font-size: 20px; font-weight: 700; color: var(--brand); letter-spacing: -0.01em; }
          .brand-tag { font-size: 14px; color: var(--muted); font-style: italic; }
          h1 { font-size: 28px; line-height: 1.25; margin: 28px 0 8px; letter-spacing: -0.02em; }
          .count {
            display: inline-block; margin: 0 0 14px;
            background: var(--brand); color: #ffffff;
            font-size: 14px; font-weight: 600;
            padding: 4px 12px; border-radius: 999px;
          }
          .intro { color: var(--muted); max-width: 70ch; margin: 0 0 8px; }
          .note { color: var(--muted); font-size: 14px; max-width: 70ch; margin: 0 0 28px; }
          .table-scroll { overflow-x: auto; -webkit-overflow-scrolling: touch; border: 1px solid var(--line); border-radius: 8px; }
          table { width: 100%; border-collapse: collapse; min-width: 640px; }
          caption { text-align: left; padding: 14px 16px; font-weight: 600; border-bottom: 1px solid var(--line); }
          th {
            text-align: left; font-size: 13px; text-transform: uppercase; letter-spacing: 0.04em;
            color: #ffffff; background: var(--brand); padding: 12px 16px; white-space: nowrap;
          }
          td { padding: 12px 16px; border-top: 1px solid var(--line); vertical-align: top; word-break: break-word; }
          tr:nth-child(even) td { background: var(--stripe); }
          td.num { color: var(--muted); width: 1%; white-space: nowrap; text-align: right; }
          td.date, td.imgs { color: var(--muted); white-space: nowrap; font-variant-numeric: tabular-nums; }
          a { color: var(--brand); text-decoration: underline; text-underline-offset: 2px; }
          a:hover, a:focus { color: #0f3a4c; }
          footer { margin-top: 28px; padding-top: 18px; border-top: 1px solid var(--line); color: var(--muted); font-size: 14px; }
          @media (max-width: 640px) {
            .wrap { padding: 24px 16px 48px; }
            h1 { font-size: 23px; }
            th, td { padding: 10px 12px; }
          }
        </style>
      </head>
      <body>
        <div class="wrap">
          <div class="brand">
            <span class="brand-name">The Building Practice Ltd.</span>
            <span class="brand-tag">...Building Spaces that Feel</span>
          </div>
          <xsl:apply-templates select="s:sitemapindex" />
          <xsl:apply-templates select="s:urlset" />
          <footer>
            Generated by The Building Practice, this XML Sitemap is intended for consumption by
            search engines.
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>

  <!-- Sitemap index -->
  <xsl:template match="s:sitemapindex">
    <h1>XML Sitemap Index</h1>
    <p class="count"><xsl:value-of select="count(s:sitemap)" /> sitemaps</p>
    <p class="intro">
      This index lists every sitemap published for
      <strong>www.buildingpractice.biz</strong>. Each child sitemap groups a single type of
      content so search engines can discover and revisit pages efficiently.
    </p>
    <p class="note">Select a sitemap below to view the URLs it contains.</p>
    <div class="table-scroll">
      <table>
        <caption>Child sitemaps</caption>
        <tr>
          <th>#</th>
          <th>Sitemap</th>
          <th>Last Modified</th>
        </tr>
        <xsl:for-each select="s:sitemap">
          <tr>
            <td class="num"><xsl:value-of select="position()" /></td>
            <td>
              <a href="{s:loc}"><xsl:value-of select="s:loc" /></a>
            </td>
            <td class="date">
              <xsl:choose>
                <xsl:when test="s:lastmod"><xsl:value-of select="substring(s:lastmod, 1, 10)" /></xsl:when>
                <xsl:otherwise>&#8212;</xsl:otherwise>
              </xsl:choose>
            </td>
          </tr>
        </xsl:for-each>
      </table>
    </div>
  </xsl:template>

  <!-- Child sitemap -->
  <xsl:template match="s:urlset">
    <xsl:variable name="imageCount" select="count(s:url/image:image)" />
    <h1>XML Sitemap</h1>
    <p class="count"><xsl:value-of select="count(s:url)" /> URLs</p>
    <p class="intro">
      This sitemap lists pages published on <strong>www.buildingpractice.biz</strong>, together
      with the date each page was last modified where that information is available.
    </p>
    <p class="note">
      Dates are shown only where a genuine modification date exists.
    </p>
    <div class="table-scroll">
      <table>
        <caption>Indexed URLs</caption>
        <tr>
          <th>#</th>
          <th>URL</th>
          <xsl:if test="$imageCount &gt; 0"><th>Images</th></xsl:if>
          <th>Last Modified</th>
        </tr>
        <xsl:for-each select="s:url">
          <tr>
            <td class="num"><xsl:value-of select="position()" /></td>
            <td>
              <a href="{s:loc}"><xsl:value-of select="s:loc" /></a>
            </td>
            <xsl:if test="$imageCount &gt; 0">
              <td class="imgs">
                <xsl:choose>
                  <xsl:when test="count(image:image) &gt; 0">
                    <xsl:value-of select="count(image:image)" />
                  </xsl:when>
                  <xsl:otherwise>&#8212;</xsl:otherwise>
                </xsl:choose>
              </td>
            </xsl:if>
            <td class="date">
              <xsl:choose>
                <xsl:when test="s:lastmod"><xsl:value-of select="substring(s:lastmod, 1, 10)" /></xsl:when>
                <xsl:otherwise>&#8212;</xsl:otherwise>
              </xsl:choose>
            </td>
          </tr>
        </xsl:for-each>
      </table>
    </div>
  </xsl:template>
</xsl:stylesheet>
`;
